version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_PROFILES_ACTIVE=postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic

